# Escribe tu código aquí :-)
import turtle
tortuga = turtle.Turtle()
tortuga.shape("turtle")
tortuga.color("red")
pantalla=turtle.Screen()
pantalla.title("Primer dibujo")
pantalla.bgcolor("blue")
for i in range(0,2):
    tortuga.forward(100)
    tortuga.right(90)
    tortuga.forward(200)
    tortuga.right(90)
tortuga.penup()
tortuga.goto(0,200)
tortuga.pendown()
tortuga.goto(50,100)
tortuga.goto(-50,100)
tortuga.goto(0,200)
