# Escribe tu código aquí :-)
import turtle
tortuga = turtle.Turtle()
tortuga.shape("turtle")
tortuga.color("red")
pantalla=turtle.Screen()
pantalla.title("Primer dibujo")
pantalla.bgcolor("blue")
tortuga.fillcolor("orange")
tortuga.goto(0,0)
def círculo():
    tortuga.circle(50)
def círculo_cabeza():
    tortuga.penup()
    tortuga.goto(0,65)
    tortuga.pendown()
    tortuga.circle(30)
def círculo_ojos():
    tortuga.penup()
    tortuga.goto(-20,100)
    tortuga.pendown()
    tortuga.circle(5)
    tortuga.penup()
    tortuga.goto(20,100)
    tortuga.circle(5)
    tortuga.pendown()
tortuga.fillcolor("orange")
tortuga.begin_fill()
círculo()
tortuga.end_fill()
tortuga.fillcolor("orange")
tortuga.begin_fill()
círculo_cabeza()
tortuga.end_fill()
círculo_ojos()
