# Escribe tu código aquí :-)
import turtle
tortuga = turtle.Turtle()
tortuga.shape("turtle")
tortuga.color("black")
pantalla=turtle.Screen()
pantalla.title("Gato negro")
pantalla.bgcolor("white")
tortuga.goto(0,0)
def círculo():
    tortuga.circle(50)
def círculo_cabeza():
    tortuga.penup()
    tortuga.goto(0,65)
    tortuga.pendown()
    tortuga.circle(30)
def círculo_ojos():
    tortuga.pendown()
    tortuga.circle(5)
def boca():
    tortuga.goto(0,90)
    for i in range(0,3):
        tortuga.right(120)
        tortuga.forward(10)
def orejas():
    for i in range(0,3):
        tortuga.right(120)
        tortuga.forward(15)
tortuga.fillcolor("black")
tortuga.begin_fill()
círculo()
tortuga.end_fill()
tortuga.fillcolor("black")
tortuga.begin_fill()
círculo_cabeza()
tortuga.end_fill()
tortuga.penup()
tortuga.goto(20,100)
tortuga.fillcolor("white")
tortuga.begin_fill()
círculo_ojos()
tortuga.end_fill()
tortuga.penup()
tortuga.goto(-20,100)
tortuga.fillcolor("white")
tortuga.begin_fill()
círculo_ojos()
tortuga.end_fill()
tortuga.fillcolor("white")
tortuga.begin_fill()
boca()
tortuga.end_fill()
tortuga.penup()
tortuga.goto(13,130)
tortuga.pendown()
tortuga.fillcolor("black")
tortuga.begin_fill()
orejas()
tortuga.end_fill()
tortuga.penup()
tortuga.goto(-22,130)
tortuga.pendown()
tortuga.fillcolor("black")
tortuga.begin_fill()
orejas()
tortuga.end_fill()
